# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Grt4Dj7FLilTeh5eNBiGSJd05xfbPlXz
"""

class Bank_account:
  def __init__(self, account_number, balance, pin):
    self._account_number = account_number
    self._balance = balance
    self._pin = pin
  def check_pin(self, input_pin):
    return input_pin == self._pin
  def deposit(self, amount):
    if amount > 0:
      self._balance += amount
      return("Deposit successful")
    else:
      return("unable to process negative deposit")
  def withdraw(self, amount):
    if amount <= self._balance:
      self._balance -= amount
      return("withdraw successful")
    else:
      return("you have insufficient funds for this transaction")
  def get_balance(self):
    return self._balance
bank_account = []
count = int(input("How many accounts? ").strip())
for i in range(count):
  print(f"\nAccount number {i+1}")
  account_number = input("Enter account number: ").strip()
  balance =int(input("Enter starting balance: ").strip())
  pin = input("Set a 4-digit PIN: ").strip()
  b_acc = Bank_account(account_number, balance, pin)
  bank_account.append(b_acc)
login_number = input("\nEnter your account number: ")
login_pin = input("Enter your PIN: ")
current_b_acc = None
for b_acc in bank_account:
  if b_acc._account_number == login_number:
    current_b_acc = b_acc
    break
if current_b_acc is None:
  print("Account not found")
else:
  if not current_b_acc.check_pin(login_pin):
    print("Incorrect PIN")
  else:
    while True:
      print("\n---Menu---")
      print("1. deposit")
      print("2. withdraw")
      print("3. Check Balance")
      print("4. Exit")
      choice = input("\nEnter your choice(1-4): ").strip()
    if choice == "1":
      amount = float(input("\nEnter amount to deposit: ").strip())
      print(current_b_acc.deposit(amount))
    elif choice == "2":
      amount = float(input("\nEnter amount to withdraw: ").strip())
      print(current_b_accb.withdraw(amount))
    elif choice == "3":
      print("Your current balance is:", current_b_acc.get_balance())
    elif choice == "4":
      print("thank you for banking with us. Goodbye!")
    else:
      print("invalid choice! Please select 1-4.")

from google.colab import files
uploaded = files.upload()

!apt-get install git -y

from google.colab import files
uploaded = files.upload()

!git config --global user.name
"judeabdu"
!git config --global user.email
"abdushakuluhssenkindu@gmail.com"



!git init

!git add Bank-system.py

!git commit -m "First bank account system project"

!git commit -m "First bank account system project"

!git -c user.name="judeabdu" -c user.email="abdushakuluhssenkindu@gmail.com" commit -m "First bank account system project"

!git remote add origin https://github.com/judeabdu/Bank-system.git
!git branch -M main
!git push -u origin main

!git remote remove origin
!git remote add origin https://github.com/judeabdu/Bank-system.git

!git push -u origin main

import random
secret_number = random.randint(1,50)
print("       Number should be btwn 1 and 50 inclusive     ")
print("              you have 10 trials                    ")
print("                  Debug number:", secret_number)
for trial in range(1,11):
    Guess = int(input("\n Enter your guess number btwn 1 and 50: "))
    if Guess < 1 or Guess > 50:
        print("Ur guess is beyond range:")
    else:
        print(f"Good, ur guess is {Guess} which is")
    difference = abs(Guess - secret_number)
    if Guess == secret_number:
        print("\nCorrect, U won")
        break
    elif Guess > secret_number:
        if difference > 10:
            print("way too high")
        else:
            print("too high")
    elif Guess < secret_number:
        if difference > 10:
            print("way too low")
        else:
            print("too low")
else:
    print("Game Over, Try later, the number was", secret_number)